### ISSUE TITLE
Fix flaking sample tests

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-monitoring#153]
The sample tests are failing on master due to some issue with alert policies.  It looks like we need to figure out if we're deleting things in the right order, cleaning them up correctly, etc.

**Comment by stephenplusplus** [comment]
The flakes: https://circleci.com/gh/googleapis/nodejs-monitoring/4447

**Comment by JustinBeckwith** [comment]
Fixed in #163
