### ISSUE TITLE
Q: Does this work within a web browser?

### ISSUE THREAD

**Issue by axisofentropy** [googleapis/nodejs-monitoring#317]
Does this client library require node.js or can it work within a web browser? Thanks.

**Comment by bcoe** [comment]
@axisofentropy is't potentially possible to get some of the library working using a grpc-fallback, there's a thread [here](https://github.com/googleapis/google-cloud-node/issues/2933) that discusses the topic, and I've asked the engineer driving the work fill in some context.

**Comment by bcoe** [comment]
@axisofentropy closing this as it hasn't had a response in a while, webpack should work for bundling this modules, let us know if you bump into any issues.
