### ISSUE TITLE
Proto files include a dead link

### ISSUE THREAD

**Issue by callmehiphop** [googleapis/nodejs-monitoring#326]
Proto files include a dead link - https://github.com/googleapis/nodejs-monitoring/blob/a2dbb0b8df925317f01a193038ad520f0c8c43e7/protos/google/monitoring/v3/common.proto#L410

This is causing CI to hang on all our PRs.

**Comment by bcoe** [comment]
@callmehiphop let's add an ignore directive to our linkinator config for the time being, and I'll open an internal bug.
