### ISSUE TITLE
Add `types` field in `package.json` so code editors can support auto completion

### ISSUE THREAD

**Issue by remorses** [googleapis/nodejs-monitoring#390]
Now the package does not support typescript types because the `types` filed is missing in `package.json`

Also the type declarations are not bundled with the library and need to be generated in the release process

**Comment by minism** [comment]
Any update here?

**Comment by sofisl** [comment]
Hi there! We are publishing our types to npm (even though we are not doing so through the `types` field), so I wonder if it's something distinct about your editor. Are you still having this issue, and if so, can you tell me what editor you're using?

**Comment by remorses** [comment]
What is the types package? It would be better to bundle the types with the library given that it is not obvious what the types package name is for packages that already use the @ character

**Comment by sofisl** [comment]
It should be bundled with the library. Do you mind confirming what editor you're using?

**Comment by alexander-fenster** [comment]
@remorses Just to add here, we do bundle types within our monitoring library:

```
$ npm install @google-cloud/monitoring

> protobufjs@6.10.1 postinstall /private/tmp/mon/node_modules/protobufjs
> node scripts/postinstall

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN mon No description
npm WARN mon No repository field.
npm WARN mon No license field.

+ @google-cloud/monitoring@2.1.1
added 66 packages from 90 contributors and audited 66 packages in 9.059s
found 0 vulnerabilities

$ find node_modules/\@google-cloud/monitoring -name '*.d.ts'
node_modules/@google-cloud/monitoring/build/protos/protos.d.ts
node_modules/@google-cloud/monitoring/build/src/v3/service_monitoring_service_client.d.ts
node_modules/@google-cloud/monitoring/build/src/v3/group_service_client.d.ts
node_modules/@google-cloud/monitoring/build/src/v3/alert_policy_service_client.d.ts
node_modules/@google-cloud/monitoring/build/src/v3/notification_channel_service_client.d.ts
node_modules/@google-cloud/monitoring/build/src/v3/uptime_check_service_client.d.ts
node_modules/@google-cloud/monitoring/build/src/v3/index.d.ts
node_modules/@google-cloud/monitoring/build/src/v3/metric_service_client.d.ts
node_modules/@google-cloud/monitoring/build/src/index.d.ts
```

According to TypeScript [documentation](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) on publishing, there is no need in having `types` property in `package.json` if we do have `index.d.ts` right near our `index.js` (which is the case here). If something does not work for you, please give more details and we'll be happy to figure out what's going on.

Thank you!
