### ISSUE TITLE
Is it possible to query for incidents?

### ISSUE THREAD

**Issue by transitive-bullshit** [googleapis/nodejs-monitoring#410]
**Is your feature request related to a problem? Please describe.**

I'd like to have CRUD access to incidents related to a given alert policy without having to use the Google Cloud Console UI.

**Comment by sofisl** [comment]
Hi there; we're moving this repo to googleapis/google-cloud-node, and closing stale issues. If you're still having trouble with this, please feel free to reopen in googleapis/google-cloud-node. Thank you!
