### ISSUE TITLE
MetricsServiceClient in index.d.ts is a value not a type

### ISSUE THREAD

**Issue by elialgranti** [googleapis/nodejs-monitoring#435]
#### Environment details

  -  Typescript (any version really)
  - `@google-cloud/monitoring` version: 2.0.0

#### Steps to reproduce

When passing the `MetricServiceClient` as value to a class in Typescript you are required to specify the type.

```
class Foo {
  constructor(private client: MetricServiceClient) {}
}
```

The logical thing to do would be to import the class type definition from the top `index.d.ts` like so:

```
import { MetricServiceClient } from '@google-cloud/monitoring'
```

However there is already a value `MetricServiceClient` in `index.d.ts` which is instantiated to the type of `MetricServiceClient` ([see here](https://github.com/googleapis/nodejs-monitoring/blob/master/src/index.ts#L23))

I assume you did so non-typescript clients can easily call the static methods of the class, but it means importing the class definition from the source file:

```
import { MetricServiceClient } from "@google-cloud/monitoring/build/src/v3"
```
which looks fragile to me.

I can think of no good solution that would not break compatibility, but maybe you could add top level files to import the type definitions:

```
import { MetricServiceClient } from "@google-cloud/monitoring/metric_service_client"
```

Or copy `v3/index.d.ts` to the root and then we can have :

```
import { MetricServiceClient } from "@google-cloud/monitoring/v3"
```

**Comment by bcoe** [comment]
@elialgranti I think this approach might work?

```
import { MetricServiceClient } from '@google-cloud/monitoring'

class Foo {
  constructor(private client: InstanceType<typeof MetricServiceClient>) {
  }
}

const client = new MetricServiceClient()
new Foo(client);
```

**Comment by elialgranti** [comment]
@bcoe thanks. Yes that  works.

**Comment by bcoe** [comment]
awesome, closing this if you're unblocked. Let me know if I'm mistaken.
