### ISSUE TITLE
Appropriate for monitoring high frequency events?

### ISSUE THREAD

**Issue by Jimbly** [googleapis/nodejs-monitoring#482]
I'm migrating a product into Google Cloud, and am used to a monitoring API (such as Graphite) that handles being called thousands to tens of thousands of times a second per process (e.g. on every WebSocket message call `metrics.add('num_requests', 1)` and `metrics.put('bytes_read', buf.len)`), and the monitoring library and/or agent aggregate the appropriate data so it sends at most a few packets per second and the result is that I can monitor/graph requests per minute or max(bytes_read) per hour, etc.  However, it looks like this library is perhaps sending an HTTP request on every `createTimeSeries` call, which would be prohibitively expensive.  If I'm not misunderstanding this, is there an appropriate high-level library to use that would handle aggregation appropriately on top of this (is that even possible)? Or a different GCP service that we should be using? I've seen some references to Prometheus on GCP, would that be a better fit?

**Comment by syedashrafulla** [comment]
For your use case, a better option is [OpenCensus](https://cloud.google.com/monitoring/custom-metrics/open-census). OpenCensus does the local aggregation you've seen in other libraries or agents.

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
