### ISSUE TITLE
Support conditionMonitoringQueryLanguage in Alert condition

### ISSUE THREAD

**Issue by nicolasgere** [googleapis/nodejs-monitoring#489]
Hi there, 
Stackdriver api support conditionMonitoringQueryLanguag as condition type, which is not the case in this package. Do you know when it will be available?

**Comment by nicolasgere** [comment]
No update there? @bcoe

**Comment by bcoe** [comment]
@nicolasgere unfortunately no updates as to when we can prioritize this feature.

**Comment by sofisl** [comment]
Hi there; we're moving this repo to googleapis/google-cloud-node, and closing stale issues. If you're still having trouble with this, please feel free to reopen in googleapis/google-cloud-node. Thank you!
