### ISSUE TITLE
Allow `uptimeCheckConfigs` to enable "log check failures" to match UI option

### ISSUE THREAD

**Issue by georgecrawford** [googleapis/nodejs-monitoring#517]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
I'm using Terraform to automate the creation of Uptime Checks in Google Cloud (https://console.cloud.google.com/monitoring/uptime). However, there's no option to enable the "Log check failures" option which I see in the UI:
<img width="557" alt="2021:01:28-16 10 35" src="https://user-images.githubusercontent.com/84737/106167639-50425080-6185-11eb-98f9-7039f389e376.png">

I've raised a ticket on the Terraform repo ([here](https://github.com/hashicorp/terraform-provider-google/issues/8324)), but since this option isn't mentioned in the [docs for `uptimeCheckConfigs` in the REST API](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.uptimeCheckConfigs), I assume this is an upstream REST API issue.

 **Describe the solution you'd like**
`Resource: UptimeCheckConfig` should include an additional boolean top-level field "logCheckFailures: bool".

 **Describe alternatives you've considered**
My Terraform script currently informs the user to enable this option manually in the UI for each new uptime check that was created, which is not ideal!

**Comment by sofisl** [comment]
Hi there! I'd recommend opening a bug directly with the[API](https://issuetracker.google.com/savedsearches/559785), since this repo is more for the client library. Thanks!
