### ISSUE TITLE
`filter` does not exist in type `IListUptimeCheckConfigsRequest`

### ISSUE THREAD

**Issue by danmichaelo** [googleapis/nodejs-monitoring#644]
[ListUptimeCheckConfigsRequest](https://cloud.google.com/monitoring/api/ref_v3/rpc/google.monitoring.v3#google.monitoring.v3.ListUptimeCheckConfigsRequest) (gRPC) and [projects.uptimeCheckConfigs.list](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.uptimeCheckConfigs/list) (REST) both provide a `filter` parameter, but this doesn't seem to be available from this client.

#### Environment details

  - OS: (not relevant)
  - Node.js version: 16.17.1
  - npm version: 8.19.2
  - `@google-cloud/monitoring` version: 3.0.2

#### Steps to reproduce

```typescript
import monitoring from "@google-cloud/monitoring";

const credentials = ...;
const projectPath = ...;

const uptimeCheckClient = new monitoring.UptimeCheckServiceClient({ credentials });
uptimeCheckClient.listUptimeCheckConfigs({ 
  parent: projectPath, 
  filter: '...',
});
```

Result: `'filter' does not exist in type 'IListUptimeCheckConfigsRequest'`

**Comment by danmichaelo** [comment]
Please let me know if there is a better place to report this! Having digged a little deeper, it seems to me like the client library is somehow generated from the interface definitions at https://github.com/googleapis/googleapis , but that repo doesn't have an issue tracker.

**Comment by bcoe** [comment]
Hello @danmichaelo,

The `.proto` definitions in `googleapis/googleapis` are maintained by the Cloud Monitoring engineering team. A good alternate place to open an issue would be on their issue tracker, listed [here](https://cloud.google.com/support/docs/issue-trackers).
